version: '3.8'

services:
  spring-api:
    build: .
    container_name: spring-web-api
    ports:
      - "8080:8080"
    environment:
      - ACTIVE_PROFILE=docker
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
    external: true  # Eğer önceden oluşturulmuş bir ağı kullanıyorsanız
